item {
  id: 1
  name: 'kantong'
}
item {
  id: 2
  name: 'kertas'
}
item {
  id: 3
  name: 'piring'
}
item {
  id: 4
  name: 'kardus'
}
item {
  id: 5
  name: 'cup'
}
item {
  id: 6
  name: 'kaleng'
}
item {
  id: 7
  name: 'botol'
}